### PR TITLE
Add flag to change the set of invalid JIRA card statuses

### PR DESCRIPTION
**Pull request by SimonStJG**

### CODE REVIEW

**Comment by RichardBradley** [comment]
Nice, thanks

**Comment by RichardBradley** [comment]
Does this assume recent Java?

We're running on Java 8 and this caused:

```
ompiling 12 Java sources to /tmp/build/40b7cd15/todo-checker-src/target/scala-2.10/classes...
[error] /tmp/build/40b7cd15/todo-checker-src/src/main/java/com/softwire/todos/GitCheckout.java:48: cannot find symbol
[error]   symbol:   method of(java.lang.String,java.lang.String,java.lang.String)
[error]   location: interface java.util.List
[error]                 List<String> output = git(List.of("ls-remote", "--get-url", "origin"));
[error] /tmp/build/40b7cd15/todo-checker-src/src/main/java/com/softwire/todos/GitCheckout.java:75: cannot find symbol
[error]   symbol:   method of(java.lang.String,java.lang.String,java.lang.String)
[error]   location: interface java.util.List
[error]             return Iterables.getOnlyElement(git(List.of("symbolic-ref", "--short", "HEAD")));
[error] /tmp/build/40b7cd15/todo-checker-src/src/main/java/com/softwire/todos/GitCheckout.java:83: cannot find symbol
[error]   symbol:   method of(int)
[error]   location: interface java.util.Set
[error]         return git(cmd, Set.of(0));
[error] /tmp/build/40b7cd15/todo-checker-src/src/main/java/com/softwire/todos/TodoCheckerMain.java:38: cannot find symbol
[error]   symbol:   method of(java.lang.String,java.lang.String,java.lang.String,java.lang.String)
[error]   location: interface java.util.List
[error]     private static final List<String> DEFAULT_INVALID_CARD_STATUSES = List.of("In Test", "Passed test", "UAT", "Done");
[error] /tmp/build/40b7cd15/todo-checker-src/src/main/java/com/softwire/todos/TodoFinder.java:27: cannot find symbol
[error]   symbol:   method of(java.lang.String,java.lang.String,java.lang.String)
[error]   location: interface java.util.List
[error]         List<String> matches = gitCheckout.git(List.of("grep", "-iIwn", "todo"), Set.of(0, 1));  // todo-checker-ignore
[error] /tmp/build/40b7cd15/todo-checker-src/src/main/java/com/softwire/todos/TodoFinder.java:27: cannot find symbol
[error]   symbol:   method of(int,int)
[error]   location: interface java.util.Set
[error]         List<String> matches = gitCheckout.git(List.of("grep", "-iIwn", "todo"), Set.of(0, 1));  // todo-checker-ignore
[info] /tmp/build/40b7cd15/todo-checker-src/src/main/java/com/softwire/todos/JiraProjectOptionHandler.java: /tmp/build/40b7cd15/todo-checker-src/src/main/java/com/softwire/todos/JiraProjectOptionHandler.java uses unchecked or unsafe operations.
```

Maybe the build.sbt should specify the required Java lang level, to avoid doubt?

I think I can update our build to j11; I'll take a look

**Comment by SimonStJG** [comment]
Just sent you an email about this, our messages must have crossed paths!

Yes, List.of is new in Java 9.  Happy to update the build.sbt if you let me know a min version, probably won't have time to do this immediately today, though.

**Comment by RichardBradley** [comment]
Fixed at c501a87

**Pull request merged**
